### ISSUE TITLE
Is name of repository successful?

### ISSUE THREAD

**Issue by optozorax** [obeijaflor/physics-formula-sheet#4]
If I want to find `Physics Formulas` on GitHub, I type `Physics Formulas GitHub` in Google, or `Physics Formulas` in GitHub search. I think it would complicated to find in Google or GitHub this repository for its words, because name of repository is `PhysFormulaSheet`. Maybe it is worth to rename repository to `physics-formulas` or `physics-formulas-sheet`? I think after renaming it would more easy to find this repository.

For example, great number of repositories named as I offer:
[hex-color-generator](https://github.com/iRaul/hex-color-generator)
[neural-style](https://github.com/jcjohnson/neural-style)
[awesome-cpp](https://github.com/fffaraz/awesome-cpp)
[sublime-monokai-extended](https://github.com/jonschlinkert/sublime-monokai-extended)
[markdown-editor](https://github.com/jbt/markdown-editor)

Sorry for bad English.

**Comment by rachelsfba** [comment]
Done
